spring.application.name=backend
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/base_sesion
spring.datasource.username=root
spring.datasource.password=1234


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.expiration-ms=120000
app.jwt.secret=TuClaveSecretaMuyLargaYSeguraQueNadieDebeSaber123